"use client"

import type React from "react"

import { useState } from "react"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import {
  Calendar,
  Truck,
  User,
  Package,
  MapPin,
  Clock,
  FileText,
  Download,
  Grid3X3,
  DollarSign,
  CheckCircle,
  AlertTriangle,
} from "lucide-react"

interface UsedPart {
  id: string
  name: string
  sku: string
  count: number
  binLocation: string
  cost_price?: number
  unit_price?: number
}

interface CompletedJob {
  map(arg0: (part: any, index: any) => React.JSX.Element): React.ReactNode
  id: string
  job_name: string
  date: string
  truck: {
    id: string
    name: string
    license_plate?: string
    location?: string
  }
  truck_name?: string
  license_plate?: string
  parts: UsedPart[]
  parts_used_count: number
  technician?: string
  created_by_name?: string
  status: string
}

interface CompletedJobDetailsModalProps {
  job?: CompletedJob
  children: React.ReactNode
}

export function CompletedJobDetailsModal({ job, children }: CompletedJobDetailsModalProps) {

  const [open, setOpen] = useState(false)

  // ✅ Calculate total parts cost dynamically
  const totalPartsCost = job?.parts?.reduce((sum, part) => {
    const partCost = (part.cost_price || 0) * (part.count || 0)
    return sum + partCost
  }, 0) || 0
  const laborCost = 125.0;
  const taxRate = 0.08;
  const taxAmount = (totalPartsCost + laborCost) * taxRate
  const totalJobCost = totalPartsCost + laborCost + taxAmount

  // Financial breakdown
  const financialDetails = {
    partsCost: totalPartsCost,
    laborCost,
    subtotal: totalPartsCost + laborCost,
    taxRate: taxRate * 100,
    taxAmount,
    totalCost: totalJobCost,
    commission: totalJobCost * 0.03, // 3% commission
    credit: totalJobCost * 0.25, // 25% credit
  }


  //   const generateJobPDF = () => {
  //     const pdfContent = `
  // JOB COMPLETION REPORT
  // ====================

  // Job ID: ${job?.id}
  // Job Name: ${job?.job_name}
  // Date: ${job?.date
  //         ? new Date(job.date).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" })
  //         : "N/A"}

  // TRUCK & TECHNICIAN:
  // Truck: ${job?.truck_name} (${job?.license_plate})
  // Technician: ${job?.technician}

  // PARTS LIST:
  // ${job && job.parts
  //         .map(
  //           (part: any, index: number) => `
  // ${index + 1}. ${part.name} (${part.sku || "N/A"})
  //    Bin Location: ${part.binLocation || "N/A"}
  //    Quantity: ${part.count}x
  //    Unit Cost: $${part.unit_price?.toFixed(2) || "0.00"}
  //    Total: $${part.cost_price?.toFixed(2) || "0.00"}`
  //         )
  //         .join("\n\n")}

  // FINANCIAL SUMMARY:
  // Parts Cost: $${financialDetails.partsCost.toFixed(2)}
  // Labor Cost: $${financialDetails.laborCost.toFixed(2)}
  // Subtotal: $${financialDetails.subtotal.toFixed(2)}
  // Tax (${financialDetails.taxRate}%): $${financialDetails.taxAmount.toFixed(2)}
  // Total Job Cost: $${financialDetails.totalCost.toFixed(2)}

  // Commission (3%): $${financialDetails.commission.toFixed(2)}
  // Technician Credit (25%): $${financialDetails.credit.toFixed(2)}

  // Generated by TruxtoK System
  // ${new Date().toLocaleString()}
  //     `.trim()

  //     const blob = new Blob([pdfContent], { type: "text/plain" })
  //     const url = URL.createObjectURL(blob)

  //     const a = document.createElement("a")
  //     a.href = url
  //     a.download = `job?-${job?.id}-${job?.job_name.replace(/[^a-zA-Z0-9]/g, "-")}.txt`
  //     document.body.appendChild(a)
  //     a.click()
  //     document.body.removeChild(a)
  //     URL.revokeObjectURL(url)
  //   }

  const generateJobPDF = () => {
    const pdfContent = `
JOB COMPLETION REPORT
====================

Job ID: ${job?.id}
Job Name: ${job?.job_name}
Date: ${job?.date
        ? new Date(job.date).toLocaleDateString("en-US", { year: "numeric", month: "short", day: "numeric" })
        : "N/A"}

TRUCK & TECHNICIAN:
Truck: ${job?.truck_name} (${job?.license_plate})
Technician: ${job?.technician}

PARTS LIST:
${job && job.parts
        .map(
          (part: any, index: number) => `
${index + 1}. ${part.name} (${part.sku || "N/A"})
 Bin Location: ${part.binLocation || "N/A"}
 Quantity: ${part.count}x
 Unit Cost: $${part.unit_price?.toFixed(2) || "0.00"}
 Total: $${part.cost_price?.toFixed(2) || "0.00"}`
        )
        .join("\n\n")}

Generated by TruxtoK System
${new Date().toLocaleString()}
  `.trim()

    const blob = new Blob([pdfContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)

    const a = document.createElement("a")
    a.href = url
    a.download = `job?-${job?.id}-${job?.job_name.replace(/[^a-zA-Z0-9]/g, "-")}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const getStatusColor = (status: string) => {
    switch (status.toLowerCase()) {
      case "completed":
        return "bg-green-100 text-green-800"
      case "in-progress":
        return "bg-blue-100 text-blue-800"
      case "pending":
        return "bg-yellow-100 text-yellow-800"
      default:
        return "bg-gray-100 text-gray-800"
    }
  }

  const getPriorityColor = (priority: string) => {
    switch (priority.toLowerCase()) {
      case "high":
        return "bg-red-100 text-red-800"
      case "medium":
        return "bg-orange-100 text-orange-800"
      case "low":
        return "bg-green-100 text-green-800"
      default:
        return "bg-gray-100 text-gray-800"
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="sm:max-w-[900px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5" />
            Job Details - {job?.id}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6">
          {/* Job Overview */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Job Overview</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex flex-wrap items-center gap-2 mb-4">
                <Badge className={job?.status && getStatusColor(job?.status)}>
                  <CheckCircle className="h-3 w-3 mr-1" />
                  {job?.status}
                </Badge>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <p className="text-sm font-medium text-gray-500">Job Name</p>
                  <p className="text-base font-semibold">{job?.job_name}</p>
                </div>
                <div>
                  <p className="text-sm font-medium text-gray-500">Date</p>
                  <p className="text-base flex items-center gap-1">
                    <Calendar className="h-4 w-4 text-gray-400" />
                    {job?.date ? new Date(job.date).toLocaleDateString("en-US", {
                      year: "numeric",
                      month: "short",
                      day: "numeric",
                    }) : "N/A"}
                  </p>
                </div>
                <div>
                  <p className="text-sm font-medium text-gray-500">Job ID</p>
                  <p className="text-base">{job?.id}</p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Truck & Technician */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg flex items-center gap-2">
                <Truck className="h-4 w-4" />
                Truck & Technician Details
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between p-4 bg-blue-50 rounded-lg">
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 bg-[#10294B] rounded-lg flex items-center justify-center">
                    <Truck className="h-6 w-6 text-white" />
                  </div>
                  <div>
                    <p className="text-sm text-gray-600">Truck Name: {job?.truck_name}</p>
                    <p className="text-sm text-gray-600">License: {job?.license_plate}</p>
                  </div>
                </div>
                <div className="text-right">
                  <div className="flex items-center gap-2 mb-1">
                    <User className="h-4 w-4 text-gray-400" />
                    <span className="font-medium">{job?.created_by_name}</span>
                  </div>
                  <p className="text-sm text-gray-600">Lead Technician</p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Parts Used */}
          <Card>
            <CardHeader>
              <CardTitle className="text-lg flex items-center gap-2">
                <Package className="h-4 w-4" />
                Parts Used ({job?.parts_used_count} total items)
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {job && job.parts.map((part, index) => (
                  <div key={part.id} className="border rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex-1">
                        <div className="flex items-center gap-2">
                          <h4 className="font-medium">{part.name}</h4>
                          <Badge variant="outline">{part.sku}</Badge>
                        </div>
                        <div className="text-sm text-gray-600 flex items-center gap-1 mt-1">
                          <Grid3X3 className="h-3 w-3" />
                          {part.binLocation}
                        </div>
                      </div>
                      <div className="text-right">
                        {/* Show cost_price */}
                        <p className="text-sm text-gray-600">
                          {part.count}x @ ${part?.cost_price ? part.cost_price.toFixed(2) : "0.00"}
                        </p>

                        {/* Show count × cost_price */}
                        <p className="font-semibold text-lg">
                          ${(part?.cost_price && part.count) ? (part.count * part.cost_price).toFixed(2) : "0.00"}
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Financial Details */}
          {/* <Card>
            <CardHeader>
              <CardTitle className="text-lg flex items-center gap-2">
                <DollarSign className="h-4 w-4" />
                Financial Breakdown
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {/* Cost Breakdown */}
          {/* <div className="space-y-3">
                    <h4 className="font-medium text-gray-900">Cost Breakdown</h4>
                    <div className="space-y-2">
                      <div className="flex justify-between">
                        <span className="text-gray-600">Parts Cost:</span>
                        <span className="font-medium">${financialDetails.partsCost.toFixed(2)}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Labor Cost:</span>
                        <span className="font-medium">${financialDetails.laborCost.toFixed(2)}</span>
                      </div>
                      <Separator />
                      <div className="flex justify-between">
                        <span className="text-gray-600">Subtotal:</span>
                        <span className="font-medium">${financialDetails.subtotal.toFixed(2)}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Tax ({financialDetails.taxRate}%):</span>
                        <span className="font-medium">${financialDetails.taxAmount.toFixed(2)}</span>
                      </div>
                      <Separator />
                      <div className="flex justify-between text-lg">
                        <span className="font-semibold">Total Job Cost:</span>
                        <span className="font-bold text-[#10294B]">${financialDetails.totalCost.toFixed(2)}</span>
                      </div>
                    </div>
                  </div> */}

          {/* Earnings */}
          {/* <div className="space-y-3">
                    <h4 className="font-medium text-gray-900">Technician Earnings</h4>
                    <div className="bg-green-50 p-4 rounded-lg space-y-2">
                      <div className="flex justify-between">
                        <span className="text-gray-600">Commission (3%):</span>
                        <span className="font-medium text-blue-600">${financialDetails.commission.toFixed(2)}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Credit Earned (25%):</span>
                        <span className="font-medium text-green-600">${financialDetails.credit.toFixed(2)}</span>
                      </div>
                      <Separator />
                      <div className="flex justify-between text-lg">
                        <span className="font-semibold">Total Earnings:</span>
                        <span className="font-bold text-green-600">
                          ${(financialDetails.commission + financialDetails.credit).toFixed(2)}
                        </span>
                      </div>
                    </div>
                  </div>
                </div> */}

          {/* Summary Stats */}
          {/* <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-4 border-t">
                  <div className="text-center p-3 bg-blue-50 rounded-lg">
                    <div className="text-2xl font-bold text-blue-600">{job?.parts_used_count}</div>
                    <div className="text-sm text-blue-600">Parts Used</div>
                  </div>
                  <div className="text-center p-3 bg-green-50 rounded-lg">
                    <div className="text-2xl font-bold text-green-600">${financialDetails.totalCost.toFixed(0)}</div>
                    <div className="text-sm text-green-600">Job Value</div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>  */}

          {/* Action Buttons */}
          <div className="flex flex-col md:flex-row gap-3 pt-4 border-t">
            <Button onClick={generateJobPDF} className="flex-1 bg-[#E3253D] hover:bg-[#E3253D]/90">
              <Download className="h-4 w-4 mr-2" />
              Download Detailed Report
            </Button>
            <Button variant="outline" onClick={() => setOpen(false)} className="flex-1 bg-transparent">
              Close
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
