"use client"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import {
  Calendar,
  MapPin,
  Package,
  DollarSign,
  Building2,
  Clock,
  CheckCircle,
  AlertCircle,
  Download,
  MessageSquare,
  Truck,
  User,
  Grid3X3,
  Mail,
  Phone,
  CheckCircle2,
} from "lucide-react"
import { useState } from "react"
import { ContactTechnicianModal } from "./contact-technician-modal"

interface OrderItem {
  id: string
  inventoryItemId: string
  inventoryItem: {
    id: string
    name: string
    category: string
    unit: string
    part_number: string
    brand: string
    standardLevel: number
    lowStockThreshold: number
    notes: string
  }
  requestedQuantity: number
  truckId?: string
  truckName?: string
  binId?: string
  binName?: string
  currentStock?: number
  reason: string
  unitCost?: number
  totalCost?: number
}

interface Technician {
  id: string
  firstName: string
  lastName?: string
  email: string
  phone?: string
  role: string
}

interface PreviousOrder {
  id: string
  orderId: string
  date: string
  truckId: string
  truckName: string
  isStockItem: boolean
  items: OrderItem[]
  technician: Technician
  totalItems: number
  status: string
  orderValue?: number
  commission?: number
  creditEarned?: number
  supplyHouse?: string
  urgency?: string
  deliveryDate?: string
  trackingNumber?: string
  notes?: string
}

interface PreviousOrderDetailsModalProps {
  order: PreviousOrder
  isOpen: boolean
  onClose: () => void
}

const statusConfig = {
  pending: { color: "bg-yellow-100 text-yellow-800", icon: Clock },
  processing: { color: "bg-blue-100 text-blue-800", icon: Package },
  shipped: { color: "bg-purple-100 text-purple-800", icon: Truck },
  delivered: { color: "bg-green-100 text-green-800", icon: CheckCircle },
  cancelled: { color: "bg-red-100 text-red-800", icon: AlertCircle },
}

const urgencyConfig = {
  low: { color: "bg-gray-100 text-gray-800" },
  normal: { color: "bg-blue-100 text-blue-800" },
  high: { color: "bg-orange-100 text-orange-800" },
  urgent: { color: "bg-red-100 text-red-800" },
}

export function PreviousOrderDetailsModal({ order, isOpen, onClose }: PreviousOrderDetailsModalProps) {
  const StatusIcon = statusConfig[order.status.toLowerCase() as keyof typeof statusConfig]?.icon || Clock

  // Calculate financial details
  const orderValue =
    order.orderValue || order.items.reduce((sum, item) => sum + (item.totalCost || item.requestedQuantity * 25), 0)
  const commission = order.commission || orderValue * 0.03
  const creditEarned = order.creditEarned || commission * 0.25
  const [showContactSupport, setShowContactSupport] = useState(false);

  //   const generateOrderPDF = () => {
  //     const pdfContent = `
  // DETAILED ORDER REPORT
  // ====================

  // Order Information:
  // - Order ID: ${order.id}
  // - Date: ${new Date(order.date).toLocaleString()}
  // - Status: ${order.status.toUpperCase()}
  // - Truck: ${order.truckName}
  // - Urgency: ${order.urgency || "Normal"}

  // Technician Details:
  // - Name: ${order.technician.firstName + ' ' + order.technician.lastName}
  // - Email: ${order.technician.email}
  // - Phone: ${order.technician.phone}

  // Items Ordered:
  // ${order.items
  //         .map(
  //           (item, index) => `
  // ${index + 1}. ${item.inventoryItem.name}
  //    - Part Number: ${item.inventoryItem.part_number}
  //    - Brand: ${item.inventoryItem.brand}
  //    - Category: ${item.inventoryItem.category}
  //    - Quantity: ${item.requestedQuantity} ${item.inventoryItem.unit}
  //    - Unit Cost: $${(item.unitCost || 25).toFixed(2)}
  //    - Total Cost: $${(item.totalCost || item.requestedQuantity * 25).toFixed(2)}
  //    - Bin Location: ${item.binName || "General Storage"}
  //    - Current Stock: ${item.currentStock || "N/A"}
  //    - Reason: ${item.reason}
  // `,
  //         )
  //         .join("")}

  // Financial Summary:
  // - Total Order Value: $${orderValue.toFixed(2)}
  // - Platform Commission (3%): $${commission.toFixed(2)}
  // - Credit Earned (25% of commission): $${creditEarned.toFixed(2)}
  // - Net Platform Revenue: $${(commission - creditEarned).toFixed(2)}

  // ${order.trackingNumber ? `Tracking Number: ${order.trackingNumber}` : ""}
  // ${order.deliveryDate ? `Delivery Date: ${order.deliveryDate}` : ""}
  // ${order.notes ? `Notes: ${order.notes}` : ""}

  // Generated by TruxtoK System
  // ${new Date().toLocaleString()}
  //     `.trim()

  //     const blob = new Blob([pdfContent], { type: "text/plain" })
  //     const url = URL.createObjectURL(blob)
  //     const a = document.createElement("a")
  //     a.href = url
  //     a.download = `order-details-${order.id}.txt`
  //     document.body.appendChild(a)
  //     a.click()
  //     document.body.removeChild(a)
  //     URL.revokeObjectURL(url)
  //   }
  const generateOrderPDF = () => {
    const pdfContent = `
DETAILED ORDER REPORT
====================

Order Information:
- Order ID: ${order.id}
- Date: ${new Date(order.date).toLocaleString()}
- Status: ${order.status.toUpperCase()}
- Truck: ${order.truckName}

Technician Details:
- Name: ${order.technician.firstName + ' ' + order.technician.lastName}
- Email: ${order.technician.email}
- Phone: ${order.technician.phone}

Items Ordered:
${order.items
        .map(
          (item, index) => `
${index + 1}. ${item.inventoryItem.name}
 - Part Number: ${item.inventoryItem.part_number}
 - Brand: ${item.inventoryItem.brand}
 - Category: ${item.inventoryItem.category}
 - Quantity: ${item.requestedQuantity} ${item.inventoryItem.unit}
 - Unit Cost: $${(item.unitCost || 25).toFixed(2)}
 - Total Cost: $${(item.totalCost || item.requestedQuantity * 25).toFixed(2)}
 - Bin Location: ${item.binName || "General Storage"}
 - Current Stock: ${item.currentStock || "N/A"}
 - Reason: ${item.reason}
`,
        )
        .join("")}

Generated by TruxtoK System
${new Date().toLocaleString()}
  `.trim()

    const blob = new Blob([pdfContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `order-details-${order.id}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }
  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[95vh] sm:max-h-[90vh] overflow-y-auto p-0 sm:p-6">
        <DialogHeader className="px-4 sm:px-0 pt-4 sm:pt-0">
          <DialogTitle className="text-lg sm:text-xl font-bold text-[#10294B] flex items-center gap-2">
            <Package className="h-4 w-4 sm:h-5 sm:w-5" />
            <span className="truncate">Order Details - {order.orderId}</span>
          </DialogTitle>
          <DialogDescription className="text-sm">Complete order information and breakdown</DialogDescription>
        </DialogHeader>

        <div className="space-y-4 sm:space-y-6 px-4 sm:px-0">
          {/* Order Header */}
          <Card className="mx-0">
            <CardHeader className="pb-3 px-4 sm:px-6">
              <div className="flex flex-col space-y-3">
                <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-3">
                  <div className="flex flex-wrap gap-2">
                    <Badge className={`${statusConfig[order.status.toLowerCase() as keyof typeof statusConfig]?.color} text-xs`}>
                      <StatusIcon className="h-3 w-3 mr-1" />
                      {order.status.charAt(0).toUpperCase() + order.status.slice(1)}
                    </Badge>
                    {/* <Badge
                      className={`${urgencyConfig[(order.urgency?.toLowerCase() || "normal") as keyof typeof urgencyConfig]?.color} text-xs`}
                    >
                      {(order.urgency || "Normal").toUpperCase()} Priority
                    </Badge> */}
                  </div>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
                  <div className="flex items-center gap-2 text-gray-600">
                    <Calendar className="h-4 w-4 flex-shrink-0" />
                    <span className="truncate">Ordered: {new Date(order.date).toLocaleDateString()}</span>
                  </div>
                  <div className="flex items-center gap-2 text-gray-600">
                    <Truck className="h-4 w-4 flex-shrink-0" />
                    <span className="truncate">Truck: {order.truckName}</span>
                  </div>
                </div>
              </div>
            </CardHeader>
            <CardContent className="pt-0 px-4 sm:px-6">
              <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
                <div className="text-center p-3 bg-blue-50 rounded-lg">
                  <Package className="h-5 w-5 sm:h-6 sm:w-6 text-[#10294B] mx-auto mb-1" />
                  <div className="text-base sm:text-lg font-bold text-[#10294B]">{order.totalItems}</div>
                  <p className="text-xs text-gray-600">Total Items</p>
                </div>
                <div className="text-center p-3 bg-green-50 rounded-lg">
                  <DollarSign className="h-5 w-5 sm:h-6 sm:w-6 text-green-600 mx-auto mb-1" />
                  <div className="text-base sm:text-lg font-bold text-green-600">${orderValue.toFixed(2)}</div>
                  <p className="text-xs text-gray-600">Order Value</p>
                </div>
                <div className="text-center p-3 bg-purple-50 rounded-lg">
                  <DollarSign className="h-5 w-5 sm:h-6 sm:w-6 text-purple-600 mx-auto mb-1" />
                  <div className="text-base sm:text-lg font-bold text-purple-600">${commission.toFixed(2)}</div>
                  <p className="text-xs text-gray-600">Commission</p>
                </div>
                <div className="text-center p-3 bg-red-50 rounded-lg">
                  <DollarSign className="h-5 w-5 sm:h-6 sm:w-6 text-[#E3253D] mx-auto mb-1" />
                  <div className="text-base sm:text-lg font-bold text-[#E3253D]">${creditEarned.toFixed(2)}</div>
                  <p className="text-xs text-gray-600">Credit Earned</p>
                </div>
              </div>
            </CardContent>
          </Card>

          {!order.isStockItem ? ('') : 
          (<div className="mx-0">
            <div className="flex items-center gap-2 bg-green-50 border border-green-200 text-green-700 text-sm font-medium px-4 py-3 rounded-lg">
              <CheckCircle2 className="h-4 w-4 text-green-600 flex-shrink-0" />
              The item from this order has been successfully updated in your inventory.
            </div>
          </div>)}

          {/* Technician Information */}
          <Card className="mx-0">
            <CardHeader className="pb-3 px-4 sm:px-6">
              <CardTitle className="flex items-center gap-2 text-base sm:text-lg">
                <User className="h-4 w-4" />
                Technician Information
              </CardTitle>
            </CardHeader>
            <CardContent className="px-4 sm:px-6">
              <div className="flex flex-col sm:flex-row sm:items-center space-y-3 sm:space-y-0 sm:space-x-3">
                <div className="w-12 h-12 sm:w-10 sm:h-10 bg-[#10294B] rounded-full flex items-center justify-center text-white font-bold text-sm flex-shrink-0">
                  {order.technician.firstName
                    .split(" ")
                    .map((n) => n[0])
                    .join("")}
                </div>
                <div className="flex-1 min-w-0">
                  <h3 className="font-semibold text-sm sm:text-base truncate">{order.technician.firstName + " " + order.technician.lastName}</h3>
                  <p className="text-gray-600 text-xs sm:text-sm">{order.technician.role} Specialist</p>
                  <div className="grid grid-cols-1 gap-1 mt-2">
                    <div className="flex items-center gap-1 text-xs text-gray-500">
                      <Mail className="h-3 w-3 flex-shrink-0" />
                      <span className="truncate">{order.technician.email}</span>
                    </div>
                    {order.technician.phone && (
                      <div className="flex items-center gap-1 text-xs text-gray-500">
                        <Phone className="h-3 w-3 flex-shrink-0" />
                        <span className="truncate">{order.technician.phone}</span>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Items Breakdown */}
          <Card className="mx-0">
            <CardHeader className="px-4 sm:px-6">
              <CardTitle className="flex items-center gap-2 text-base sm:text-lg">
                <Package className="h-4 w-4 sm:h-5 sm:w-5" />
                Items Ordered ({order.items.length} items)
              </CardTitle>
            </CardHeader>
            <CardContent className="px-4 sm:px-6">
              <div className="space-y-3 sm:space-y-4">
                {order.items.map((item, index) => {
                  const unitCost = item.unitCost || 25
                  const totalCost = item.totalCost || item.requestedQuantity * unitCost

                  return (
                    <div key={item.id} className="border rounded-lg p-3 sm:p-4 bg-gray-50">
                      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
                        <div className="flex-1 min-w-0">
                          <div className="flex flex-col sm:flex-row sm:items-center gap-2 mb-2">
                            <span className="font-semibold text-[#10294B] text-sm sm:text-base">
                              {index + 1}. {item.inventoryItem.name}
                            </span>
                            <Badge variant="outline" className="text-xs w-fit">
                              {item.inventoryItem.category}
                            </Badge>
                          </div>
                          <div className="text-xs sm:text-sm text-gray-600 mb-2 space-y-1">
                            <div>
                              <span className="font-medium">Part #:</span> {item.inventoryItem.part_number}
                            </div>
                            <div>
                              <span className="font-medium">Unit:</span> {item.inventoryItem.unit}
                            </div>
                          </div>
                          {item.binName && (
                            <div className="flex items-center gap-1 text-xs sm:text-sm text-blue-600 mb-2">
                              <Grid3X3 className="h-3 w-3 flex-shrink-0" />
                              <span className="truncate">
                                Bin: {item.binName} • Stock: {item.currentStock || "N/A"}
                              </span>
                            </div>
                          )}
                          <div className="text-xs sm:text-sm text-gray-700">
                            <span className="font-medium">Reason:</span> {item.reason}
                          </div>
                        </div>
                        <div className="text-right sm:text-right flex-shrink-0">
                          <div className="text-base sm:text-lg font-bold text-[#10294B]">${totalCost.toFixed(2)}</div>
                          <div className="text-xs sm:text-sm text-gray-500">
                            {item.requestedQuantity} {item.inventoryItem.unit} × ${unitCost.toFixed(2)}
                          </div>
                        </div>
                      </div>
                    </div>
                  )
                })}
              </div>
            </CardContent>
          </Card>

          {/* Financial Breakdown */}
          {/* <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <DollarSign className="h-5 w-5" />
                Financial Breakdown
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                <div className="flex justify-between items-center text-lg">
                  <span>Total Order Value</span>
                  <span className="font-bold">${orderValue.toFixed(2)}</span>
                </div>
                <Separator />
                <div className="space-y-2">
                  <div className="flex justify-between items-center text-blue-600">
                    <span>Platform Commission (3%)</span>
                    <span className="font-semibold">${commission.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between items-center text-green-600">
                    <span>Credit to Technician (25% of commission)</span>
                    <span className="font-semibold">${creditEarned.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between items-center text-purple-600">
                    <span>Net Platform Revenue</span>
                    <span className="font-semibold">${(commission - creditEarned).toFixed(2)}</span>
                  </div>
                </div>
                <Separator />
                <div className="flex justify-between items-center font-bold text-lg">
                  <span>Amount Due to Supply House</span>
                  <span className="text-[#E3253D]">${(orderValue - commission).toFixed(2)}</span>
                </div>
              </div>
            </CardContent>

            <ContactTechnicianModal
              isOpen={showContactSupport}
              onClose={() => setShowContactSupport(false)}
              technician={{
                name: process.env.NEXT_PUBLIC_ADMIN_NAME || "TruxTok Admin",
                email: process.env.NEXT_PUBLIC_ADMIN_EMAIL || "support@truxtok.com",
                phone: process.env.NEXT_PUBLIC_ADMIN_PHONE || "",
              }}
              orderId={order.orderId}
              role="Admin"
            />
          </Card> */}

          {/* Actions */}
          <div className="flex flex-col sm:flex-row gap-3 pt-4 border-t px-4 sm:px-0">
            <Button onClick={generateOrderPDF} className="flex-1 bg-[#E3253D] hover:bg-[#E3253D]/90 text-sm sm:text-base">
              <Download className="h-4 w-4 mr-2" />
              <span className="hidden sm:inline">Download Detailed Report</span>
              <span className="sm:hidden">Download Report</span>
            </Button>
            <Button variant="outline" className="flex-1 bg-transparent text-sm sm:text-base"
              onClick={() => setShowContactSupport(true)}
            >
              <MessageSquare className="h-4 w-4 mr-2" />
              <span className="hidden sm:inline">Contact Support</span>
              <span className="sm:hidden">Support</span>
            </Button>
            <Button variant="outline" onClick={onClose} className="bg-transparent text-sm sm:text-base sm:px-6">
              Close
            </Button>
          </div>
        </div>
      </DialogContent>
      <ContactTechnicianModal
        isOpen={showContactSupport}
        onClose={() => setShowContactSupport(false)}
        technician={{
          name: process.env.NEXT_PUBLIC_ADMIN_NAME || "TruxTok Admin",
          email: process.env.NEXT_PUBLIC_ADMIN_EMAIL || "truxtok@mailinator.com",
          phone: process.env.NEXT_PUBLIC_ADMIN_PHONE || "",
        }}
        orderId={order.orderId}
        role="Admin"
      />
    </Dialog>
  )
}
